name: Facepunch Style COmmits
author: wildflowericecoffee
description: >
  Send notifications to Discord using a webhook.
inputs:
  webhookUrl:
    description: Discord webhook URL. Should be stored in a secret and inserted as a context expression.
    required: true
runs:
  using: 'node12'
  main: 'index.js'
branding:
  color: orange
  icon: alert-triangle
